### ISSUE TITLE
Provide output argument meta-data to allow generic callback for methods 

### ISSUE THREAD

**Issue by jonasgreen88** [open62541/open62541#4801]
## Description

Imagine a use case where all methods share a generic method callback. This callback may translate OPC UA method calls to some equivalent feature of a sub-system in the application. We have such a use case and we need to know the OPC UA data type of the output arguments to set the correct data type in the output argument variants (in our case the sub-system's data types maps 1:N to OPC UA types).

We can solve this with the current open62541 implementation and find the OutputArguments node of the Method node by duplicating the implementation of `getArgumentsVariableNode()` in ua_services_method.c. https://github.com/open62541/open62541/blob/223d3d5d55e6bbc771f9e0d6bfe2af0facc6f395/src/server/ua_services_method.c#L22 

But to avoid copying internal code to a callback implementation we would like to see the method callback provide this information. Our proposal is to update the method callback definition by adding a new argument `UA_Argument *outputArgs` which should provide the value of the OutputArguments node.

```
typedef UA_StatusCode
(*UA_MethodCallback)(UA_Server *server, const UA_NodeId *sessionId,
                     void *sessionContext, const UA_NodeId *methodId,
                     void *methodContext, const UA_NodeId *objectId,
                     void *objectContext, size_t inputSize,
                     const UA_Variant *input, size_t outputSize,
                     UA_Variant *output, UA_Argument *outputArgs);
```

We can provide a PR once we agreed to a solution.

## Background Information / Reproduction Steps
N/A

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue
